blank_issues_enabled: false
contact_links:
  - name: Feature Request or Idea
    url: https://github.com/carlreid/StreamMaster/discussions/new?category=ideas
    about: Open a Discussion for new Features or Ideas
  - name: Have a question or need help?
    url: https://github.com/carlreid/StreamMaster/discussions/new?category=q-a
    about: Please use Discussions for support.
