name: Create release and publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [arm64, arm32, amd64]

    env:
      REF_NAME: ${{ github.ref_name }}

    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update && sudo apt-get -y upgrade
            sudo apt-get install -yq git curl build-essential
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install git curl -y
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # Install required dependencies for macOS
            # Add commands specific to macOS environment
            echo "macOS setup"
          fi

      - name: Build project
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          git checkout $latest_tag

          dotnet restore "StreamMasterAPI/StreamMasterAPI.csproj"
          dotnet build "StreamMasterAPI/StreamMasterAPI.csproj" -c Debug >/dev/null

          cd streammasterwebui
          npm install
          npm run build
          mkdir -p "$GITHUB_WORKSPACE/publish/wwwroot/"
          cp -R build/* "$GITHUB_WORKSPACE/publish/wwwroot/"
          cd ..

          cd StreamMasterAPI
          dotnet publish --no-restore "StreamMasterAPI.csproj" -c Debug -o "$GITHUB_WORKSPACE/publish" /p:UseAppHost=false >/dev/null

      - name: Zip publish directory
        run: |
          cd publish
          zip -r ../streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.zip .

      - name: Generate SHA256 hash for Zip archive
        run: |
          cd publish
          sha256sum ../streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.zip > ../streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.zip.sha256

      - name: Tar publish directory
        run: |
          cd publish
          tar -czvf ../streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.tar.gz .

      - name: Generate SHA256 hash for Tar archive
        run: |
          cd publish
          sha256sum ../streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.zip > ../streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.tar.gz.sha256

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          tag_name: v${{ env.GitVersion_SemVer }}
          release_name: v${{ env.GitVersion_SemVer }}
          draft: false
          prerelease: false
      - name: Upload Release Asset (zip)
        id: upload-release-asset-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.zip
          asset_name: streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.zip
          asset_content_type: application/zip

      - name: Upload SHA256 hash for zip
        id: upload-sha256-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.zip.sha256
          asset_name: streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.zip.sha256
          asset_content_type: text/plain

      - name: Upload Release Asset (tar.gz)
        id: upload-release-asset-tar-gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.tar.gz
          asset_name: streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload SHA256 hash for tar.gz
        id: upload-sha256-tar-gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.tar.gz.sha256
          asset_name: streammaster-${{ env.GitVersion_SemVer }}-${{ matrix.os }}-${{ matrix.architecture }}.tar.gz.sha256
          asset_content_type: text/plain
