name: Native Code
on:
  workflow_dispatch:
    inputs:
      comments:
        description: "Comments"
        required: true
        default: "Manual build Actions"

permissions:
  contents: read

env:
  REGISTRY_IMAGE: senexcrenshaw/streammaster

jobs:
  build-streammaster:
    runs-on: ubuntu-latest
